### PR TITLE
Fix namespace of cross-db macros from dbt_utils to dbt

### PR DESCRIPTION
**Pull request by stumelius**
**Are you a current Fivetran customer?** 

**What change(s) does this PR introduce?** 

Since dbt_utils 1.0.0 the cross-db macros are in the dbt namespace https://github.com/dbt-labs/dbt-utils/releases/tag/1.0.0.

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] Buildkite  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by fivetran-joemarkiewicz — CHANGES_REQUESTED** [review]
Hi @stumelius thank you so much for taking the time to notice these missed namespace updates. I am surprised our process missed these hanging macros. Nevertheless, I really appreciate you catching this and taking the time to open a PR to address the bug.

While this update looks great, there are a few other updates needed in order to merge into the `main` branch and be released in a patch:
- [ ] Would you be able to update the semantic version of the package to increase to `0.8.1` within the `dbt_project.yml` and `integration_tests/dbt_project.yml` files.
- [ ] Finally, would you be able to update the CHANGELOG for the v0.8.1 release to include your update. Also be sure to include yourself in a Contributor entry!

Once those updates are applied, this will be good to merge and release!

**Comment by erika-e** [comment]
Oh man I came here to make this PR and someone beat me to it! 😁 Commenting to follow along since this is blocking our upgrade to the latest versions of everything.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the note @erika-e and raising that this is blocking other users. As that is the case, I may elect to make the required changes directly in order to prioritize getting this fix out the door.

**Review by fivetran-joemarkiewicz — APPROVED** [review]
Thanks again @stumelius for opening this PR to address the dispatch issue we originally missed in the migration update.

As this is a high priority fix, I opted to apply the updates in order to try and push the patch as soon as possible. With this, I will kick off our internal process to merge and release these updates. Thanks again for helping to open the PR and work to keep our packages updated! 🎉

**Comment by stumelius** [comment]
@fivetran-joemarkiewicz Thanks for taking care of this! I was out for a long weekend so it's good that you went ahead and did the update :)

**Pull request merged**
